[2025-09-11 13:24:30,423] {processor.py:153} INFO - Started process (PID=1242) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:24:30,424] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:24:30,425] {logging_mixin.py:115} INFO - [2025-09-11 13:24:30,425] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:24:30,441] {logging_mixin.py:115} INFO - [2025-09-11 13:24:30,441] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 18
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:24:30,442] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:24:30,456] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.036 seconds
[2025-09-11 13:25:01,319] {processor.py:153} INFO - Started process (PID=1271) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:25:01,320] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:25:01,321] {logging_mixin.py:115} INFO - [2025-09-11 13:25:01,321] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:25:01,329] {logging_mixin.py:115} INFO - [2025-09-11 13:25:01,328] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 18
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:25:01,329] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:25:01,343] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.026 seconds
[2025-09-11 13:25:31,374] {processor.py:153} INFO - Started process (PID=1291) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:25:31,375] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:25:31,376] {logging_mixin.py:115} INFO - [2025-09-11 13:25:31,376] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:25:31,395] {logging_mixin.py:115} INFO - [2025-09-11 13:25:31,394] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 18
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:25:31,395] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:25:31,409] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.037 seconds
[2025-09-11 13:26:01,724] {processor.py:153} INFO - Started process (PID=1320) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:26:01,725] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:26:01,725] {logging_mixin.py:115} INFO - [2025-09-11 13:26:01,725] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:26:01,733] {logging_mixin.py:115} INFO - [2025-09-11 13:26:01,733] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 18
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:26:01,733] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:26:01,749] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.027 seconds
[2025-09-11 13:26:32,209] {processor.py:153} INFO - Started process (PID=1348) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:26:32,210] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:26:32,210] {logging_mixin.py:115} INFO - [2025-09-11 13:26:32,210] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:26:32,224] {logging_mixin.py:115} INFO - [2025-09-11 13:26:32,223] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 18
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:26:32,225] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:26:32,240] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.033 seconds
[2025-09-11 13:27:03,124] {processor.py:153} INFO - Started process (PID=1369) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:27:03,125] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:27:03,126] {logging_mixin.py:115} INFO - [2025-09-11 13:27:03,126] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:27:03,135] {logging_mixin.py:115} INFO - [2025-09-11 13:27:03,134] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 18
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:27:03,135] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:27:03,150] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.029 seconds
[2025-09-11 13:27:36,020] {processor.py:153} INFO - Started process (PID=1398) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:27:36,020] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:27:36,021] {logging_mixin.py:115} INFO - [2025-09-11 13:27:36,021] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:27:36,031] {logging_mixin.py:115} INFO - [2025-09-11 13:27:36,030] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 18
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:27:36,031] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:27:36,047] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.030 seconds
[2025-09-11 13:28:08,928] {processor.py:153} INFO - Started process (PID=1427) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:28:08,929] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:28:08,930] {logging_mixin.py:115} INFO - [2025-09-11 13:28:08,930] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:28:08,938] {logging_mixin.py:115} INFO - [2025-09-11 13:28:08,938] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 18
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:28:08,939] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:28:08,954] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.027 seconds
[2025-09-11 13:28:40,969] {processor.py:153} INFO - Started process (PID=1448) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:28:40,970] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:28:40,970] {logging_mixin.py:115} INFO - [2025-09-11 13:28:40,970] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:28:40,982] {logging_mixin.py:115} INFO - [2025-09-11 13:28:40,981] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 18
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:28:40,982] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:28:40,995] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.029 seconds
[2025-09-11 13:29:13,873] {processor.py:153} INFO - Started process (PID=1477) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:29:13,874] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:29:13,875] {logging_mixin.py:115} INFO - [2025-09-11 13:29:13,875] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:29:13,885] {logging_mixin.py:115} INFO - [2025-09-11 13:29:13,885] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 18
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:29:13,885] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:29:13,901] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.031 seconds
[2025-09-11 13:29:46,790] {processor.py:153} INFO - Started process (PID=1506) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:29:46,790] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:29:46,791] {logging_mixin.py:115} INFO - [2025-09-11 13:29:46,791] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:29:46,801] {logging_mixin.py:115} INFO - [2025-09-11 13:29:46,800] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 18
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:29:46,801] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:29:46,816] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.029 seconds
[2025-09-11 13:29:51,815] {processor.py:153} INFO - Started process (PID=1507) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:29:51,816] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:29:51,816] {logging_mixin.py:115} INFO - [2025-09-11 13:29:51,816] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:29:51,825] {logging_mixin.py:115} INFO - [2025-09-11 13:29:51,824] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 19
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:29:51,825] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:29:51,839] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.026 seconds
[2025-09-11 13:30:21,899] {processor.py:153} INFO - Started process (PID=1537) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:30:21,900] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:30:21,901] {logging_mixin.py:115} INFO - [2025-09-11 13:30:21,901] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:30:21,916] {logging_mixin.py:115} INFO - [2025-09-11 13:30:21,915] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 19
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:30:21,916] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:30:21,934] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.038 seconds
[2025-09-11 13:30:52,243] {processor.py:153} INFO - Started process (PID=1566) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:30:52,244] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:30:52,245] {logging_mixin.py:115} INFO - [2025-09-11 13:30:52,245] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:30:52,259] {logging_mixin.py:115} INFO - [2025-09-11 13:30:52,259] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 19
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:30:52,260] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:30:52,274] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.033 seconds
[2025-09-11 13:31:22,380] {processor.py:153} INFO - Started process (PID=1586) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:31:22,381] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:31:22,382] {logging_mixin.py:115} INFO - [2025-09-11 13:31:22,382] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:31:22,396] {logging_mixin.py:115} INFO - [2025-09-11 13:31:22,396] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 19
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:31:22,397] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:31:22,410] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.032 seconds
[2025-09-11 13:31:52,935] {processor.py:153} INFO - Started process (PID=1615) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:31:52,936] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:31:52,937] {logging_mixin.py:115} INFO - [2025-09-11 13:31:52,937] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:31:52,947] {logging_mixin.py:115} INFO - [2025-09-11 13:31:52,946] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 19
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:31:52,947] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:31:52,962] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.028 seconds
[2025-09-11 13:32:23,005] {processor.py:153} INFO - Started process (PID=1635) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:32:23,007] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:32:23,007] {logging_mixin.py:115} INFO - [2025-09-11 13:32:23,007] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:32:23,016] {logging_mixin.py:115} INFO - [2025-09-11 13:32:23,016] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 19
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:32:23,017] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:32:23,031] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.028 seconds
[2025-09-11 13:32:53,893] {processor.py:153} INFO - Started process (PID=1664) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:32:53,893] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:32:53,894] {logging_mixin.py:115} INFO - [2025-09-11 13:32:53,894] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:32:53,902] {logging_mixin.py:115} INFO - [2025-09-11 13:32:53,902] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 19
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:32:53,903] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:32:53,917] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.027 seconds
[2025-09-11 13:33:23,985] {processor.py:153} INFO - Started process (PID=1684) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:33:23,985] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:33:23,986] {logging_mixin.py:115} INFO - [2025-09-11 13:33:23,986] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:33:23,996] {logging_mixin.py:115} INFO - [2025-09-11 13:33:23,996] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 19
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:33:23,997] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:33:24,010] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.028 seconds
[2025-09-11 13:33:54,092] {processor.py:153} INFO - Started process (PID=1713) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:33:54,092] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:33:54,093] {logging_mixin.py:115} INFO - [2025-09-11 13:33:54,093] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:33:54,107] {logging_mixin.py:115} INFO - [2025-09-11 13:33:54,106] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 19
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:33:54,107] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:33:54,120] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.030 seconds
[2025-09-11 13:34:24,162] {processor.py:153} INFO - Started process (PID=1733) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:34:24,164] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:34:24,164] {logging_mixin.py:115} INFO - [2025-09-11 13:34:24,164] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:34:24,178] {logging_mixin.py:115} INFO - [2025-09-11 13:34:24,177] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 19
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:34:24,178] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:34:24,194] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.034 seconds
[2025-09-11 13:34:54,263] {processor.py:153} INFO - Started process (PID=1763) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:34:54,264] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:34:54,265] {logging_mixin.py:115} INFO - [2025-09-11 13:34:54,265] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:34:54,275] {logging_mixin.py:115} INFO - [2025-09-11 13:34:54,274] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 19
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:34:54,275] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:34:54,290] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.029 seconds
[2025-09-11 13:35:24,403] {processor.py:153} INFO - Started process (PID=1784) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:35:24,404] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:35:24,405] {logging_mixin.py:115} INFO - [2025-09-11 13:35:24,405] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:35:24,423] {logging_mixin.py:115} INFO - [2025-09-11 13:35:24,422] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 19
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:35:24,423] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:35:24,441] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.041 seconds
[2025-09-11 13:35:54,471] {processor.py:153} INFO - Started process (PID=1814) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:35:54,472] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:35:54,473] {logging_mixin.py:115} INFO - [2025-09-11 13:35:54,473] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:35:54,482] {logging_mixin.py:115} INFO - [2025-09-11 13:35:54,481] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 19
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:35:54,482] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:35:54,496] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.027 seconds
[2025-09-11 13:36:24,606] {processor.py:153} INFO - Started process (PID=1835) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:36:24,606] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:36:24,607] {logging_mixin.py:115} INFO - [2025-09-11 13:36:24,607] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:36:24,615] {logging_mixin.py:115} INFO - [2025-09-11 13:36:24,615] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 19
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:36:24,616] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:36:24,631] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.027 seconds
[2025-09-11 13:36:54,751] {processor.py:153} INFO - Started process (PID=1865) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:36:54,752] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:36:54,752] {logging_mixin.py:115} INFO - [2025-09-11 13:36:54,752] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:36:54,761] {logging_mixin.py:115} INFO - [2025-09-11 13:36:54,761] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 19
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:36:54,762] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:36:54,774] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.025 seconds
[2025-09-11 13:37:25,664] {processor.py:153} INFO - Started process (PID=1894) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:37:25,665] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:37:25,665] {logging_mixin.py:115} INFO - [2025-09-11 13:37:25,665] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:37:25,678] {logging_mixin.py:115} INFO - [2025-09-11 13:37:25,677] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 19
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:37:25,678] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:37:25,691] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.029 seconds
[2025-09-11 13:37:56,246] {processor.py:153} INFO - Started process (PID=1915) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:37:56,247] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:37:56,247] {logging_mixin.py:115} INFO - [2025-09-11 13:37:56,247] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:37:56,255] {logging_mixin.py:115} INFO - [2025-09-11 13:37:56,255] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 19
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:37:56,256] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:37:56,271] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.027 seconds
[2025-09-11 13:38:26,406] {processor.py:153} INFO - Started process (PID=1945) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:38:26,407] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:38:26,408] {logging_mixin.py:115} INFO - [2025-09-11 13:38:26,407] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:38:26,417] {logging_mixin.py:115} INFO - [2025-09-11 13:38:26,417] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 19
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:38:26,418] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:38:26,432] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.029 seconds
[2025-09-11 13:38:57,032] {processor.py:153} INFO - Started process (PID=1968) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:38:57,033] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:38:57,033] {logging_mixin.py:115} INFO - [2025-09-11 13:38:57,033] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:38:57,044] {logging_mixin.py:115} INFO - [2025-09-11 13:38:57,043] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 19
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:38:57,044] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:38:57,059] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.029 seconds
[2025-09-11 13:39:27,991] {processor.py:153} INFO - Started process (PID=1999) to work on /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:39:27,992] {processor.py:641} INFO - Processing file /opt/airflow/dags/weekly_transform.py for tasks to queue
[2025-09-11 13:39:27,993] {logging_mixin.py:115} INFO - [2025-09-11 13:39:27,993] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:39:28,020] {logging_mixin.py:115} INFO - [2025-09-11 13:39:28,020] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/weekly_transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weekly_transform.py", line 19
    with DAG(dag_id="Weekly_transformation", default_args=default_args, catchup=False) as dag:
       ^
IndentationError: expected an indented block
[2025-09-11 13:39:28,021] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/weekly_transform.py
[2025-09-11 13:39:28,036] {processor.py:161} INFO - Processing /opt/airflow/dags/weekly_transform.py took 0.047 seconds
